const cities = [
    "Palanpur",
    "Deesa",
    "Patan",
    "Siddhpur",
    "Mehsana",
    "Vijapur",
    "Unjha",
    "Visnagar",
    "Kheralu",
    "Vadnagar",
 
    "Surat",
    "Navsari",
    "Valsad",
    "Vapi",
    "Daman",
    "Silvassa",
    "Bharuch",
    "Ankleshwar",
    "Vyara",
    "Ahwa",
    "Godhra",
    "Dahod",
    "Lunawada",
    "Santrampur",
    "Halol",
    "Kalol (Panchmahal)",
    "Jhalod",
    "Devgadh Baria",
    "Rajkot",
    "Jamnagar",
    "Junagadh",
    "Porbandar",
    "Bhavnagar",
    "Amreli",
    "Morbi",
    "Gondal",
    "Surendranagar",
    "Maliya",
    "Mandvi (Kutch)",
    "Bhuj",
    "Anjar",
    "Mundra",
    "Dhrol",
    "Okha",
    "Dwarka",
    "Ahmedabad",
    "Gandhinagar",
    "Vadodara",
    "Nadiad",
    "Anand",
    "Borsad",
    "Dakor",
    "Umreth",
    "Halvad",
    "Mahemdavad"
  ]


export default cities;
